context:
  version: "0.21.0"

package:
  name: hex2dfu
  version: ${{ version }}

source:
  git: https://github.com/rusefi/hex2dfu
  branch: rusefi_prod
  

build:
  script:
    - if: win
      then: |
        gcc hex2dfu.c -o hex2dfu.exe -static -static-libgcc -static-libstdc++
        mkdir -p %LIBRARY_BIN%
        cp hex2dfu.exe %LIBRARY_BIN%/
      else: |
        gcc hex2dfu.c -o hex2dfu
        mkdir -p $PREFIX/bin
        cp hex2dfu $PREFIX/bin/

about:
  homepage: https://github.com/rusefi/hex2dfu
  summary: Simple command line tool to convert file format from Intel HEX to STM32 DFU.