context:
  version: "4.2"

package:
  name: dosfstools
  version: ${{ version }}

source:
  - if: not win
    then:
      url: https://github.com/dosfstools/dosfstools/releases/download/v${{ version }}/dosfstools-${{ version }}.tar.gz
      sha256: 64926eebf90092dca21b14259a5301b7b98e7b1943e8a201c7d726084809b527
      patches:
        - if: osx
          then: fix-macos-sysmacros.patch
  - if: win
    then:
      url: https://repo.msys2.org/msys/x86_64/dosfstools-${{ version }}-1-x86_64.pkg.tar.zst
      sha256: a37cc088eb77356a53a505a4175f8d301bacaf803808518f2cc88cef0f2ef906
      target_directory: msys2_pkg

build:
  number: 3
  script:
    - if: linux
      then: |
        ./configure \
          --prefix="${PREFIX}" \
          --sbindir="${PREFIX}/bin" \
          --enable-compat-symlinks \
          --disable-dependency-tracking
        make
        make install
    - if: osx
      then: |
        export ACLOCAL_PATH="${BUILD_PREFIX}/share/gettext/m4:${BUILD_PREFIX}/share/aclocal:${ACLOCAL_PATH}"
        autoreconf --force --install --verbose \
          -I "${BUILD_PREFIX}/share/gettext/m4" \
          -I "${BUILD_PREFIX}/share/aclocal"
        ./configure \
          --prefix="${PREFIX}" \
          --sbindir="${PREFIX}/bin" \
          --enable-compat-symlinks \
          --without-udev
        make
        make install
    - if: win
      then: |
        xcopy /E /I /Y msys2_pkg\usr\bin\* "%PREFIX%\bin\"

requirements:
  build:
    - if: not win
      then:
        - ${{ compiler("c") }}
        - make
    - if: osx
      then:
        - autoconf
        - automake
        - gettext
        - gettext-tools
        - pkg-config
  run:
  - if: win
    then:
      - m2-msys2-runtime
      - m2-libiconv

tests:
  - script:
    - |
      mkfs.fat --help
      fsck.fat --help
      fatlabel --help

about:
  homepage: https://github.com/dosfstools/dosfstools
  summary: The dosfstools package is a collection of utilities for creating and checking MS-DOS FAT filesystems.
  license: GPL-2.0-only
  license_file:
    - if : not win
      then: COPYING
    - if: win
      then: msys2_pkg/usr/share/licenses/dosfstools/COPYING
